{% set version = "0.1-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rebus
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rebus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rebus/rebus_{{ version }}.tar.gz
  sha256: 2d3df9da8d95c7ed299052f8cfd849ac4beae7c187ca779997033bf04c6d4357

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1005
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-rebus.base >=0.0_3
    - r-rebus.datetimes
    - r-rebus.numbers
    - r-rebus.unicode >=0.0_2
  run:
    - r-base
    - r-rebus.base >=0.0_3
    - r-rebus.datetimes
    - r-rebus.numbers
    - r-rebus.unicode >=0.0_2

test:
  commands:
    - $R -e "library('rebus')"           # [not win]
    - "\"%R%\" -e \"library('rebus')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rebus
  dev_url: https://github.com/richierocks/rebus
  license: Unlimited
  license_family: Other
  license_file:
    - LICENSE-UNLIMITED
  summary: Build regular expressions piece by piece using human readable code. This package is designed for interactive use.  For package development, use the rebus.* dependencies.

extra:
  recipe-maintainers:
    - conda-forge/r
